package version

// Version is the running desktop build.
// Release binaries are stamped from the Git tag via -ldflags; unstamped
// local builds stay "dev" so you do not edit this file for each release.
var Version = "dev"
